In [25]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
from sklearn.linear_model import LinearRegression

In [14]:
data = pd.read_csv('50_Startups.csv')
data.head()

R&D Spend  Administration  Marketing Spend       State     Profit
0  165349.20       136897.80        471784.10    New York  192261.83
1  162597.70       151377.59        443898.53  California  191792.06
2  153441.51       101145.55        407934.54     Florida  191050.39
3  144372.41       118671.85        383199.62    New York  182901.99
4  142107.34        91391.77        366168.42     Florida  166187.94

In [15]:
real_x = data.iloc[:,0:4].values
real_y = data.iloc[:,4].values
real_y[:5]

array([192261.83, 191792.06, 191050.39, 182901.99, 166187.94])

In [19]:
le  =LabelEncoder()
real_x[:,3] = le.fit_transform(real_x[:,3])
oneHE = OneHotEncoder(categorical_features=[3])
real_x = oneHE.fit_transform(real_x).toarray()
real_x

array([[1.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 1.0000000e+00,
        1.3689780e+05, 4.7178410e+05],
       [1.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 0.0000000e+00,
        1.5137759e+05, 4.4389853e+05],
       [1.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 0.0000000e+00,
        1.0114555e+05, 4.0793454e+05],
       ...,
       [1.0000000e+00, 0.0000000e+00, 1.0000000e+00, ..., 0.0000000e+00,
        1.3542692e+05, 0.0000000e+00],
       [1.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 1.0000000e+00,
        5.1743150e+04, 0.0000000e+00],
       [1.0000000e+00, 0.0000000e+00, 1.0000000e+00, ..., 0.0000000e+00,
        1.1698380e+05, 4.5173060e+04]])

In [21]:
training_x, test_x, training_y, test_y = train_test_split(real_x,real_y, test_size =0.2, random_state = 0)

In [27]:
MLR = LinearRegression()
MLR.fit(training_x,training_y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [29]:
pred_y = MLR.predict(test_x)
pred_y

array([201469.86181971,  59277.64555286,  87877.84196222,  39595.77575388,
        84721.96948277, 136502.75095744,  20063.61334411, 159452.73690128,
       113738.0666379 ,  65284.39477539])

In [34]:
test_y

array([103282.38, 144259.4 , 146121.95,  77798.83, 191050.39, 105008.31,
        81229.06,  97483.56, 110352.25, 166187.94])

In [30]:
MLR.coef_

array([ 2.60266582e+04, -2.60266584e+04, -7.24641023e+04,  5.28139073e+04,
       -4.02026930e+04, -4.32208619e+04, -3.66117456e-06, -8.45359842e+04,
        1.20749264e+04,  2.18854692e-06, -2.29319136e+04, -2.06646596e+04,
        4.19290808e+04,  1.02763830e+05,  4.27530128e+04, -7.09390038e+04,
        2.26515389e+04, -1.45519152e-11,  1.34147896e+04, -1.04209149e+04,
       -2.44424511e+04, -6.03575862e+04,  7.27595761e-12,  2.36195567e+04,
        3.63797881e-12, -3.63797881e-12, -3.19193975e+04,  1.84624192e+04,
        3.54602551e+04,  1.63962733e+04, -6.50690071e+04, -3.17388672e+04,
        2.56466337e+04,  1.10497376e+03,  2.40172660e+04, -3.51174190e+04,
        0.00000000e+00,  0.00000000e+00,  8.80049523e+03, -3.47397095e+04,
       -1.64939506e+04,  5.80474970e+04,  2.17713927e+03,  6.71079286e+04,
        1.21122597e+04,  0.00000000e+00,  5.97585898e+04,  0.00000000e+00,
        1.81290414e+04,  3.20437650e+04, -2.44681427e+03, -4.09075473e+03,
        6.53756900e+03,  

In [31]:
MLR.intercept_

-136979.46149409746